apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-evit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-evit
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-evit
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-evit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-evit
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pvae-tenant/rhtap-demo-app/hacbs-test-project-evit@sha256:d22e151d12c7237e03fbe9c8a88786c2018ef9571e59fbb16dec1375aea61d78
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
