apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-evit
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pvae-tenant/rhtap-demo-app/hacbs-test-project-evit@sha256:d22e151d12c7237e03fbe9c8a88786c2018ef9571e59fbb16dec1375aea61d78
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
